// +build !ignore_autogenerated

/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisConnection) DeepCopyInto(out *RedisConnection) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(RedisConnectionOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisConnection.
func (in *RedisConnection) DeepCopy() *RedisConnection {
	if in == nil {
		return nil
	}
	out := new(RedisConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisConnectionOptions) DeepCopyInto(out *RedisConnectionOptions) {
	*out = *in
	out.Password = in.Password
	in.Cert.DeepCopyInto(&out.Cert)
	in.Key.DeepCopyInto(&out.Key)
	in.CACert.DeepCopyInto(&out.CACert)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisConnectionOptions.
func (in *RedisConnectionOptions) DeepCopy() *RedisConnectionOptions {
	if in == nil {
		return nil
	}
	out := new(RedisConnectionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretValueFromSource) DeepCopyInto(out *RedisSecretValueFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretValueFromSource.
func (in *RedisSecretValueFromSource) DeepCopy() *RedisSecretValueFromSource {
	if in == nil {
		return nil
	}
	out := new(RedisSecretValueFromSource)
	in.DeepCopyInto(out)
	return out
}
